In [15]:
#!mamba install pandas==1.3.3 -y
#!mamba install requests==2.26.0 -y

In [42]:
# import
import glob
import pandas as pd
from datetime import datetime

In [43]:
# get the data
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_1.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_2.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/exchange_rates.csv

--2023-03-26 10:00:18--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_1.json
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.63.118.104
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.63.118.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2815 (2.7K) [application/json]
Saving to: ‘bank_market_cap_1.json.3’

bank_market_cap_1.j 100%[===================>]   2.75K  --.-KB/s    in 0s

2023-03-26 10:00:19 (20.5 MB/s) - ‘bank_market_cap_1.json.3’ saved [2815/2815]

--2023-03-26 10:00:21--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_2.json
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.63.118.104
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.63.118.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1429 (1.4K) [application/json]
Saving to: ‘bank_market_cap_2.json.3’

bank_market_cap_2.j 100%[===================>]   1.40K  --.-KB/s    in 0s

2023-03-26 10:00:22 (13.2 MB/s) - ‘bank_market_cap_2.json.3’ saved [1429/1429]

--2023-03-26 10:00:24--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/exchange_rates.csv
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.63.118.104
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.63.118.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 590 [text/csv]
Saving to: ‘exchange_rates.csv.3’

exchange_rates.csv. 100%[===================>]     590  --.-KB/s    in 0s

2023-03-26 10:00:25 (4.81 MB/s) - ‘exchange_rates.csv.3’ saved [590/590]

## Extract

In [44]:
def extract_from_json(file_to_process):
    dataframe = pd.read_json(file_to_process)
    return dataframe

In [45]:
columns=['Name','Market Cap (US$ Billion)']

In [59]:
def extract():
    return extract_from_json('bank_market_cap_1.json')

In [47]:
# Get the exchange rate for later use
ex_rates = pd.read_csv("exchange_rates.csv", index_col = 0)
ex_rates

exchange_rate = ex_rates[ex_rates.index == 'GBP'].iloc[0]['Rates']
exchange_rate

0.7323984208000001

## Transform

In [48]:
def transform(data):
    
    # 1.
    data['Market Cap (US$ Billion)'] = data['Market Cap (US$ Billion)'] * exchange_rate
    
    # 2. 
    data = data.round({'Market Cap (US$ Billion)': 3})
        
    # 3.
    data = data.rename(columns={'Market Cap (US$ Billion)': 'Market Cap (GBP$ Billion)'})
    
    return data

## Load

In [49]:
def load(data):
    data.to_csv('bank_market_cap_gbp.csv', index=False)

## Logging Function

In [50]:
def log(message):
    timestamp_format = '%Y-%h-%d-%H:%M:%S' # Year-Monthname-Day-Hour-Minute-Second
    now = datetime.now() # get current timestamp
    timestamp = now.strftime(timestamp_format)
    with open("bank_market_cap_gbp.csv","a") as f:
        f.write(timestamp + ',' + message + '\n')

## Running the ETL Process

In [51]:
log("ETL Job Started")
log("Extract phase Started")

### Extract

In [60]:
# Call the function
extracted_data = extract()
# rows
extracted_data.head(5)

                                      Name  Market Cap (US$ Billion)
0                           JPMorgan Chase                   390.934
1  Industrial and Commercial Bank of China                   345.214
2                          Bank of America                   325.331
3                              Wells Fargo                   308.013
4                  China Construction Bank                   257.399

In [61]:
# Write your code here
log("Extract phase Ended")

### Transform

In [62]:
# Write your code here
log("Transform phase started")

In [63]:
# Call the function
transformed_data = transform(extracted_data)
# Print the first 5 rows here
transformed_data.head(5)

                                      Name  Market Cap (GBP$ Billion)
0                           JPMorgan Chase                    286.319
1  Industrial and Commercial Bank of China                    252.834
2                          Bank of America                    238.272
3                              Wells Fargo                    225.588
4                  China Construction Bank                    188.519

In [64]:
# Write your code here
log("Transform phase Ended")

### Load

In [65]:
# Write your code here
log("Load phase Started")

Call the load function

In [66]:
# Write your code here
load(transformed_data)

Log the following `"Load phase Ended"`.

In [67]:
# Write your code here
log("Load phase Ended")